apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  valuesContent: |-
    # This is to install the required CRDs during the setup.
    installCRDs: true
    # This is to forward DNS lookups to cloudflare to ensure that lookups for txt records for DNS validation don't get routed back to an internal DNS server.
    extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=laura.ns.cloudflare.com:53,malcolm.ns.cloudflare.com:53
