apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: uisp
  namespace: kube-system
spec:
  chart: app-template
  targetNamespace: default
  repo: https://bjw-s.github.io/helm-charts/
  valuesContent: |-
    image:
      repository: nico640/docker-unms
      pullPolicy: IfNotPresent
      tag: latest
    env:
      TZ: America/Los_Angeles
    service:
      main:
        ports:
          http:
            port: 80
          https:
            enabled: true
            port: 443
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: uisp-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uisp
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-issuer
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: uisp.k3s.pstyler.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uisp
            port:
              name: https
  tls:
  - hosts:
    - uisp.k3s.pstyler.dev
    secretName: uisp-ingress-cert
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uisp-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 500Mi
