apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: unifi
  namespace: kube-system
spec:
  chart: unifi
  targetNamespace: default
  repo: https://k8s-at-home.com/charts/
  valuesContent: |-
    env:
      TZ: America/Los_Angeles
    image:
      tag: latest
    persistence:
      config:
        enabled: true
        mountPath: /unifi/data
        existingClaim: unifi-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-letsencrypt-issuer
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: unifi.k3s.pstyler.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi
            port:
              name: http
  tls:
  - hosts:
    - unifi.k3s.pstyler.dev
    secretName: unifi-ingress-cert
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
